### PR TITLE
Cleanup scripts section in package.json

### PR DESCRIPTION
**Pull request by djnicholson**
Fixes https://github.com/neo-project/neo-visual-tracker/issues/25

### CODE REVIEW

**Comment by devhawk** [comment]
I'm still getting the "Errors exist after running preLaunchTask 'npm: watch'." dialog on this PR. 

If I run 'npm run compile' from the command line, I get the following result:
```shell
PS> npm run compile

> neo-visual-devtracker@0.9.81-preview compile C:\Users\harry\Source\neo\seattle\visual-devtracker
> node scripts/compile.js

(node:27264) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
    at C:\Users\harry\Source\neo\seattle\visual-devtracker\scripts\compile.js:40:39
    at Object.<anonymous> (C:\Users\harry\Source\neo\seattle\visual-devtracker\scripts\compile.js:67:3)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47
(node:27264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

running npm watch from command line doesn't appear to have any errors, but the output window gets reset so I can't capture all of it:

```
> cmd.exe /c node-sass src\panels\invoke.scss -o out/panels
  cmd.exe /c node-sass src\panels\invoke.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\invoke.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\invoke.css
> cmd.exe /c node-sass src\panels\newwallet.scss -o out/panels
  cmd.exe /c node-sass src\panels\newwallet.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\newwallet.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\newwallet.css
> cmd.exe /c node-sass src\panels\tracker.scss -o out/panels
  cmd.exe /c node-sass src\panels\tracker.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\tracker.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\tracker.css
> cmd.exe /c node-sass src\panels\transfer.scss -o out/panels
  cmd.exe /c node-sass src\panels\transfer.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\transfer.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\transfer.css
> cmd.exe /c browserify out\panels\claim.main.js -o out/panels/bundles/claim.main.js
> cmd.exe /c browserify out\panels\create.main.js -o out/panels/bundles/create.main.js
> cmd.exe /c browserify out\panels\invoke.main.js -o out/panels/bundles/invoke.main.js
> cmd.exe /c browserify out\panels\newwallet.main.js -o out/panels/bundles/newwallet.main.js
> cmd.exe /c browserify out\panels\tracker.main.js -o out/panels/bundles/tracker.main.js
> cmd.exe /c browserify out\panels\transfer.main.js -o out/panels/bundles/transfer.main.js
neo-visual-tracker can now be launched
neo-visual-tracker watching for incremental changes
> cmd.exe /c tsc -watch -p ./
> cmd.exe /c node-sass src\panels\claim.scss -wo out/panels
> cmd.exe /c node-sass src\panels\common.scss -wo out/panels
> cmd.exe /c node-sass src\panels\create.scss -wo out/panels
> cmd.exe /c node-sass src\panels\dialog.scss -wo out/panels
> cmd.exe /c node-sass src\panels\invoke.scss -wo out/panels
> cmd.exe /c node-sass src\panels\newwallet.scss -wo out/panels
> cmd.exe /c node-sass src\panels\tracker.scss -wo out/panels
> cmd.exe /c node-sass src\panels\transfer.scss -wo out/panels
> cmd.exe /c watchify out\panels\claim.main.js -o out/panels/bundles/claim.main.js
> cmd.exe /c watchify out\panels\create.main.js -o out/panels/bundles/create.main.js
> cmd.exe /c watchify out\panels\invoke.main.js -o out/panels/bundles/invoke.main.js
> cmd.exe /c watchify out\panels\newwallet.main.js -o out/panels/bundles/newwallet.main.js
> cmd.exe /c watchify out\panels\tracker.main.js -o out/panels/bundles/tracker.main.js
> cmd.exe /c watchify out\panels\transfer.main.js -o out/panels/bundles/transfer.main.js
  cmd.exe /c tsc -watch -p ./ :                                                                                         
  cmd.exe /c tsc -watch -p ./ : 11:17:31 AM - Starting compilation in watch mode...
neo-visual-tracker can now be launched
neo-visual-tracker watching for incremental changes
neo-visual-tracker can now be launched
```

**Comment by djnicholson** [comment]
> If I run 'npm run compile' from the command line, I get the following result:
> 
> ```shell
> PS> npm run compile
> 
> > neo-visual-devtracker@0.9.81-preview compile C:\Users\harry\Source\neo\seattle\visual-devtracker
> > node scripts/compile.js
> 
> (node:27264) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
>     at C:\Users\harry\Source\neo\seattle\visual-devtracker\scripts\compile.js:40:39

Just pushed a fix for that.

**Comment by devhawk** [comment]
latest changes fixed my npm compile issue

**Comment by devhawk** [comment]
I'm still getting the errors exist dialog, though I am still able to run the extension by selecting the `Debug Anyway` option. There are two warnings in the compile spew (included in full below). One is for a missing license field in the project.json file and the other is a warning about fsevents not being supported on windows. That must be a dependency of a dependency, right?

```
> Executing task: npm run watch <

loading profile from ~\Source\scripts\profile.ps1

> neo-visual-devtracker@0.9.81-preview watch C:\Users\harry\Source\neo\seattle\visual-devtracker
> node scripts/compile.js -w

> cmd.exe /c npm install
  cmd.exe /c npm install : > node-sass@4.13.0 install C:\Users\harry\Source\neo\seattle\visual-devtracker\node_modules\node-sass
> node scripts/install.js
  cmd.exe /c npm install : Cached binary found at C:\Users\harry\scoop\persist\nodejs\cache\node-sass\4.13.0\win32-x64-79_binding.node
  cmd.exe /c npm install : > node-sass@4.13.0 postinstall C:\Users\harry\Source\neo\seattle\visual-devtracker\node_modules\node-sass
> node scripts/build.js
  cmd.exe /c npm install : Binary found at C:\Users\harry\Source\neo\seattle\visual-devtracker\node_modules\node-sass\vendor\win32-x64-79\binding.node
  cmd.exe /c npm install : Testing binary
  cmd.exe /c npm install : Binary is fine
E cmd.exe /c npm install : npm
E cmd.exe /c npm install : WARN neo-visual-devtracker@0.9.81-preview No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
  cmd.exe /c npm install : added 763 packages from 978 contributors and audited 15120 packages in 40.344s
  cmd.exe /c npm install : 3 packages are looking for funding
  run `npm fund` for details
  cmd.exe /c npm install : found 0 vulnerabilities
> cmd.exe /c tsc -p ./
> cmd.exe /c node-sass src\panels\claim.scss -o out/panels
  cmd.exe /c node-sass src\panels\claim.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\claim.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\claim.css
> cmd.exe /c node-sass src\panels\common.scss -o out/panels
  cmd.exe /c node-sass src\panels\common.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\common.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\common.css
> cmd.exe /c node-sass src\panels\create.scss -o out/panels
  cmd.exe /c node-sass src\panels\create.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\create.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\create.css
> cmd.exe /c node-sass src\panels\dialog.scss -o out/panels
  cmd.exe /c node-sass src\panels\dialog.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\dialog.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\dialog.css
> cmd.exe /c node-sass src\panels\invoke.scss -o out/panels
  cmd.exe /c node-sass src\panels\invoke.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\invoke.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\invoke.css
> cmd.exe /c node-sass src\panels\newwallet.scss -o out/panels
  cmd.exe /c node-sass src\panels\newwallet.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\newwallet.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\newwallet.css
> cmd.exe /c node-sass src\panels\tracker.scss -o out/panels
  cmd.exe /c node-sass src\panels\tracker.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\tracker.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\tracker.css
> cmd.exe /c node-sass src\panels\transfer.scss -o out/panels
  cmd.exe /c node-sass src\panels\transfer.scss -o out/panels : Rendering Complete, saving .css file...
  cmd.exe /c node-sass src\panels\transfer.scss -o out/panels : Wrote CSS to C:\Users\harry\Source\neo\seattle\visual-devtracker\out\panels\transfer.css
> cmd.exe /c browserify out\panels\claim.main.js -o out/panels/bundles/claim.main.js
> cmd.exe /c browserify out\panels\create.main.js -o out/panels/bundles/create.main.js
> cmd.exe /c browserify out\panels\invoke.main.js -o out/panels/bundles/invoke.main.js
> cmd.exe /c browserify out\panels\newwallet.main.js -o out/panels/bundles/newwallet.main.js
> cmd.exe /c browserify out\panels\tracker.main.js -o out/panels/bundles/tracker.main.js
> cmd.exe /c browserify out\panels\transfer.main.js -o out/panels/bundles/transfer.main.js
neo-visual-tracker can now be launched
neo-visual-tracker watching for incremental changes
> cmd.exe /c tsc -watch -p ./
> cmd.exe /c node-sass src\panels\claim.scss -wo out/panels
> cmd.exe /c node-sass src\panels\common.scss -wo out/panels
> cmd.exe /c node-sass src\panels\create.scss -wo out/panels
> cmd.exe /c node-sass src\panels\dialog.scss -wo out/panels
> cmd.exe /c node-sass src\panels\invoke.scss -wo out/panels
> cmd.exe /c node-sass src\panels\newwallet.scss -wo out/panels
> cmd.exe /c node-sass src\panels\tracker.scss -wo out/panels
> cmd.exe /c node-sass src\panels\transfer.scss -wo out/panels
> cmd.exe /c watchify out\panels\claim.main.js -o out/panels/bundles/claim.main.js
> cmd.exe /c watchify out\panels\create.main.js -o out/panels/bundles/create.main.js
> cmd.exe /c watchify out\panels\invoke.main.js -o out/panels/bundles/invoke.main.js
> cmd.exe /c watchify out\panels\newwallet.main.js -o out/panels/bundles/newwallet.main.js
> cmd.exe /c watchify out\panels\tracker.main.js -o out/panels/bundles/tracker.main.js
> cmd.exe /c watchify out\panels\transfer.main.js -o out/panels/bundles/transfer.main.js
  cmd.exe /c tsc -watch -p ./ : 8:22:51 AM - Starting compilation in watch mode...
neo-visual-tracker can now be launched
neo-visual-tracker watching for incremental changes
```

**Comment by djnicholson** [comment]
> I'm still getting the errors exist dialog, though I am still able to run the extension by selecting the `Debug Anyway` option. There are two warnings in the compile spew (included in full below). One is for a missing license field in the project.json file and the other is a warning about fsevents not being supported on windows. That must be a dependency of a dependency, right?

This is the expected output (the npm install is considered successful even though those warnings are written to stderr, and the rest of the script ran fine).  Could something else be causing your vscode to think there are errors? (Maybe those .cs files in the sample_workspace folder?)  Can you try restarting vscode?  Maybe try deleting your `out` folder?

**Comment by devhawk** [comment]
you were right about the C# files. If I *don't* do a dotnet restore, vscode reports a ton of errors in TestContract because the dependencies aren't available. So the solution there is to do the dotnet restore when vscode asks you on startup. I never do that since I didn't think it would make a difference.

**Pull request merged**
