### PR TITLE
Allow debug configs to be added to launch.json from the Invocation Panel. Fixes #45

### LINKED ISSUE #45: Allow debug configs to be added to launch.json from the Invocation Panel

### PR DESCRIPTION
**Pull request by djnicholson**

### CODE REVIEW

**Comment by devhawk** [comment]
testing this PR with https://github.com/ngdseattle/cneo-sample/, the contract appears twice in the Invoke COntract UI even though there is only one compiled AVM file in the workspace

image

**Comment by devhawk** [comment]
How do you associate UTXO assets with a contract invocation?

**Comment by devhawk** [comment]
Adding a launch configuration blows away any comments that have been added to the launch.json file. (like [this one](https://github.com/ngdseattle/cneo-sample/blob/master/.vscode/launch.json#L7))

**Comment by djnicholson** [comment]
> testing this PR with https://github.com/ngdseattle/cneo-sample/, the contract appears twice in the Invoke COntract UI even though there is only one compiled AVM file in the workspace
> 
> image

I think maybe you have a different version of the contract (same methods but different hash) deployed. This is being detected from the Neo Express JSON file and shown along side the one detected from the AVM.  Should I show the contract hash in the UI to make this more obvious?

We should resolve https://github.com/neo-project/neo-express/issues/31 and https://github.com/neo-project/neo-express/issues/20 to make the end-to-end experience better.

**Comment by djnicholson** [comment]
> How do you associate UTXO assets with a contract invocation?

I haven't done that yet (and I left https://github.com/neo-project/neo-visual-tracker/issues/46 to reflect that there are still debug options we do not support).

We need some design thought around this one, for example:
- Is it Ok for the user to just specify an amount (e.g. "20 NEO") or do we need to build some sort of UTXO picker where they pick specific UTXOs (and possible specify change)
- How should we determine what UTXOs are available? If Neo Express is already running it is easy (we make RPC calls). If Neo Express is not running do we start it? What if the user also picked a checkpoint?

**Comment by djnicholson** [comment]
> Adding a launch configuration blows away any comments that have been added to the launch.json file. (like [this one](https://github.com/ngdseattle/cneo-sample/blob/master/.vscode/launch.json#L7))

I'm using the VS Code API to change the launch.json file (see addToLaunchJson in invocationPanel.ts).  I decided this was better than doing JSON.stringify(JSON.parse(...)) as this only blows away comments within the configurations array (other comments in the file are left alone).  If we want comments within the array to be safe then I need to find a JSON parsing/serialization library that is comment-aware.

**Comment by devhawk** [comment]
> I think maybe you have a different version of the contract (same methods but different hash) deployed. This is being detected from the Neo Express JSON file and shown along side the one detected from the AVM. Should I show the contract hash in the UI to make this more obvious?

That was it - the hash in my .abi.json file doesn't match the hash in the neo-express.json file.

No, let's figure out the end-to-end w/ express better before tackling this edge case

**Comment by devhawk** [comment]
> > How do you associate UTXO assets with a contract invocation?
> 
> I haven't done that yet (and I left #46 to reflect that there are still debug options we do not support).

OK, I'm good with leaving this for #46 

> We need some design thought around this one, for example:
> 
> * Is it Ok for the user to just specify an amount (e.g. "20 NEO") or do we need to build some sort of UTXO picker where they pick specific UTXOs (and possible specify change)

I would prefer specifying the amount and using getunspents to figure out the specific UTXOs

> * How should we determine what UTXOs are available? If Neo Express is already running it is easy (we make RPC calls). If Neo Express is not running do we start it? What if the user also picked a checkpoint?

There's no way for devtracker to get the UTXO info if neo-express isn't running. we could add a command line switch for neo-express to dump the valid UTXOs for an account like get coins but offline. Let's address as part of the larger end-to-end

**Comment by devhawk** [comment]
I'm still worried about the comments getting blown away, but am approving for now. Can we open an issue to track fixing the comment issue?

**Comment by djnicholson** [comment]
> I'm still worried about the comments getting blown away, but am approving for now. Can we open an issue to track fixing the comment issue?

https://github.com/neo-project/neo-visual-tracker/issues/118

**Pull request merged**
